index.html
js/app-utils.js
js/app.js
js/trackLoadController.js

Add GTex Service Support.

---

index.html
js/trackLoadController.js

Tweaks to Annotation and GTex Select Lists.

Tweaks to Annotation and GTex Select Lists.

---

js/trackLoadController.js

Use updated gtex api

---

index.html
js/trackLoadController.js

Update Modal Titles

---

js/app-utils.js
js/app.js
js/dropboxController.js
js/encodeDataSource.js
js/fileLoadManager.js
js/fileLoadWidget.js
js/genomeLoadController.js
js/googleDriveController.js
js/modalTable.js
js/multipleFileLoadController.js
js/sessionModalController.js
js/shareController.js
js/shareHelper.js
js/trackLoadController.js

Use Strict. And prosper.

---

js/fileLoadManager.js

Track URL modal. Handle erased input values properly.

Track URL modal. Handle erased input values properly.

---

js/multipleFileLoadController.js

Bug fix for optional and missing index file. multipleFileLoadController.js

Bug fix for optional and missing index file. multipleFileLoadController.js

---

igvwebConfig.js
index.html
js/dropboxController.js
js/fileLoadManager.js
js/fileLoadWidget.js
js/genomeLoadController.js
js/main.js
js/multipleFileLoadController.js
js/sessionController.js
js/trackLoadController.js

Session Load/Save

---

js/app-google.js
js/main.js
js/multipleFileLoadController.js

Google picker api call repair.

Google picker api call repair.

---

resources/genomes.json

gorGor4, panTro4, panPan2, susScr11, and bosTau8

updated genomes.json to include 6 new genomes from ucsc

---

index.html
js/app-google.js
js/encodeDataSource.js
js/fileLoadManager.js
js/fileLoadWidget.js
js/genomeLoadController.js
js/main.js
js/modalTable.js
js/multipleFileLoadController.js
js/sessionController.js
js/shareController.js
js/shareHelper.js
js/svgController.js
js/trackLoadController.js
js/urlShortener.js
js/utils.js

undo use of igvjs module

---

js/multipleFileLoadController.js

Set the indexed field on a track config for indexable formats without index files

Set "indexed" field

---

resources/genomes.json

Genomes dropdown now sorted

---

index.html

Share modal. Copy text misalignment.

Share modal. Copy text misalignment.

---

index.html
js/multipleFileLoadController.js
js/utils.js

Support for .idx and .tbi index.

Support for .idx and .tbi index. 

---

index.html
js/encodeDataSource.js
js/modalTable.js
js/trackLoadController.js

ENCODE. Repair missing/misbehaving spinner.

ENCODE. Repair missing/misbehaving spinner.

---

index.html

ENCODE modal now jumbo size.

---

js/trackLoadController.js
resources/tracks/hg19_gtex.json
resources/tracks/trackRegistry.json

Track menu construction. GTex and Encode nolonger halt construction.

Track menu construction. GTex and Encode nolonger halt construction.

---

index.html
package-lock.json

fix igv.org link

---

js/fileLoadManager.js
js/trackLoadController.js

FileLoadManager. Handle paths with leading and/or trailing whitespace.

FileLoadManager. Handle paths with leading and/or trailing whitespace.

---

js/multipleFileLoadController.js
js/utils.js

Handle ..bgz files.

---

index.html
package-lock.json

Discard dead code

---

index.html
js/svgController.js
js/trackLoadController.js

Encode Table Split Edits

---

js/app.js
js/genomeWidgets.js
js/shareHelper.js

No longer use igv.Alert

---

js/app.js
js/genomeWidgets.js
package-lock.json
package.json

Reverts igvteam/igv-webapp#208

Revert "Eventbus Issues Fix"

---

index.html
package.json

Updated Help Menu. Share Menu - Remove email.

Updated Help Menu. Share Menu - Remove email.

---

js/app.js
js/widgets/trackWidgets.js
package.json

GTEx tracks. Enable selected track disabling

GTEx tracks. Enable selected track disabling

---

js/widgets/trackWidgets.js

Use igvxhr to support Google oAuth authentication

support authentication for data config in tracks
